image: denoland/deno:1.38.4

default:
  interruptible: true

stages:
  - test

fmt:
  stage: test
  script: deno fmt --check

lint:
  stage: test
  script: deno lint

test:
  stage: test
  script: deno task test

check:
  stage: test
  script: deno task check
